Updated azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -56,65 +56,180 @@ stages:
       condition: ne(variables['verrep'], variables['vernew'])
       displayName: Build et Push
 
-- stage: Test
+- stage: QAL_Deployment
+  condition: succeeded()
+  displayName: Deploy on QAL
   jobs:
-  - job: DeployToQAL
-    displayName: Déploiement sur namespace QAL
+  - job: QAL_Deploy
+    name: Deploy_Qal
+    displayName: Deploy on QAL
+    pool:
+      vmImage: 'ubuntu-latest'
     steps:
     - task: KubernetesManifest@0
+      name: kubeonqal
+      displayName: Deploy on QAL
       inputs:
-        action: deploy
+        action: 'deploy'
         kubernetesServiceConnection: $(kubernetesServiceEndpoint)
-        namespace: qal
-        manifests: manifest/vote-app.yml
-      condition: ne(variables['verold'], variables['vernew'])
-      displayName: Déploiement sur namespace QAL
+        namespace: 'qal'
+        manifests: '**/kubernetes/qal/*'
+    - task: Bash@3
+      name: waitingfordeploy
+      inputs:
+        targetType: 'inline'
+        script: 'sleep 30'
+    - task: Bash@3
+      inputs:
+        targetType: 'inline'
+        script: |
+          exitcode=$(curl -s -o -I -w "%{http_code}" http://brief8.uncia.fr)
+          echo "##vso[task.setvariable variable=exit]$exitcode"
+    - task: CmdLine@2
+      name: chargetest
+      condition: eq(variables['exit'], '200')
+      inputs:
+        script: |
+          seq 250 | parallel --max-args 0  --jobs 20 "curl -k -iF 'vote=free' http://brief8.uncia.fr"
+    - task: CmdLine@2
+      name: waitforcharge
+      inputs:
+        script: 'sleep 30'
+    - task: Kubernetes@1
+      inputs:
+        connectionType: Kubernetes Service Connection
+        kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
+        namespace: 'qal'
+        command: 'get'
+        useConfigurationFile: true
+        configuration: './kubernetes/qal/qal_app.yml'
+      name: qalpods
+    - task: CmdLine@2
+      name: countpod
+      inputs:
+        script: |
+          qalappcount=$(echo $QALPODS_KUBECTLOUTPUT | jq '.items[0].spec.replicas')
+          echo $qalappcount
+          echo "##vso[task.setvariable variable=countpods]$qalappcount"
 
-- stage: Canary
-  dependsOn: Test
+    - task: Kubernetes@1
+      name: deleteqal
+      condition: ne(variables['countpods'],2)
+      inputs:
+        connectionType: 'Kubernetes Service Connection'
+        kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
+        namespace: 'qal'
+        command: 'delete'
+        arguments: '-f $(System.DefaultWorkingDirectory)/kubernetes/qal/'
+
+    - task: Bash@3
+      name: yourverygood
+      condition: succeeded()
+      inputs:
+        targetType: 'inline'
+        script: 'echo "QAL DELETION"'
+
+- stage: 'Deploy_canary'
+  condition: succeeded()
+  displayName: 'Deploy Canary Release'
   jobs:
-  - job: DeployToCanary
-    displayName: Déploiement sur namespace en canary 10 sur PROD
+  - job: 'Deploy_canary'
+    displayName: 'Deployment of Canary Release'
+    pool:
+    vmImage: 'ubuntu-latest'
+    steps:
+    - task: KubernetesManifest@0
+      name: kubeonprodcanary
+      condition: succeeded()
+      inputs:
+      action: 'deploy'
+      kubernetesServiceConnection: $(kubernetesServiceEndpoint)
+      namespace: 'prod'
+      strategy: 'canary'
+      percentage: '30'
+      manifests: '**/kubernetes/canary/deployment-canary.yaml'
+
+- stage: 'ManualIntervention'
+  condition: succeeded()
+  displayName: 'In waiting of validation of working canary release'
+  jobs:
+  - job: 'waitForValidation'
+    displayName: Wait for external validation
+    pool: server
+    timeoutInMinutes: 4320 # job times out in 3 days
+    steps:
+    - task: ManualValidation@0
+      timeoutInMinutes: 1440 # task times out in 1 day
+      inputs:
+      notifyUsers: |
+      simplon.nicolasmarty@gmail.com
+      instructions: 'Please validate the build configuration and resume'
+      onTimeout: 'resume'
+
+- stage: 'DeployOnProd'
+  displayName: 'Deploy on Prod and delete Canary'
+  jobs:
+  - job: 'Deployonprod'
+    displayName: 'Deploy on Prod and delete Canary'
+    name: Deploy_Prod
+    pool:
+    vmImage: 'ubuntu-latest'
+    steps:
+    - task: Kubernetes@1
+      name: deleteprodapp
+      inputs:
+      connectionType: 'Kubernetes Service Connection'
+      kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
+      namespace: 'prod'
+      command: 'delete'
+      arguments: '-f $(System.DefaultWorkingDirectory)/kubernetes/prod/deploy_app.yml'
+
+    - task: Kubernetes@1
+      name: deployprod
+      inputs:
+      connectionType: 'Kubernetes Service Connection'
+      kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
+      namespace: 'prod'
+      command: 'apply'
+      useConfigurationFile: true
+      configuration: '$(System.DefaultWorkingDirectory)/kubernetes/prod/deploy_app.yml'
+
+    - task: Bash@3
+      name: yourdeployment
+      condition: succeeded()
+      inputs:
+      targetType: 'inline'
+      script: 'echo "DEPLOY TO PROD OK"'
+
+- stage: 'PerformanceTest'
+  condition: succeeded()
+  dependsOn: 'DeployOnProd'
+  displayName: 'Performance Test on Prod'
+  jobs:
+  - job: 'PerformanceTest'
+    name: Testing
+    displayName: 'Performance Test on Prod'
+    pool:
+      vmImage: 'ubuntu-latest'
     steps:
     - task: Kubernetes@1
       inputs:
         connectionType: Kubernetes Service Connection
         kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
-        namespace: prod
-        strategy: canary
-        percentage: "10"
-        command: apply
-        arguments: -f manifest/vote-app.yml
-        secretType: dockerRegistry
-        containerRegistryType: Azure Container Registry
-      displayName: Déploiement sur namespace en canary 10 sur PROD
+        namespace: 'prod'
+        command: 'get'
+        useConfigurationFile: true
+        configuration: '$(System.DefaultWorkingDirectory)/kubernetes/prod/deploy_app.yml'
+        name: prodpods
 
-- stage: Global
-  displayName: Global deployment
-  jobs:
-  - deployment: DeployGlobal
-    displayName: DeployGlobal
-    environment: production
-    strategy:
-      runOnce:
-        deploy:
-          steps:
-          - script: |
-              echo "Deploiment en production."
-                  displayName: Deploiement production
-                - task: ManualIntervention@1
-                  inputs:
-                    instructions: Please verify the deployment and click Approve or Reject
-                    timeoutInMinutes: 1440
-                  displayName: Manual intervention
-                    - task: Kubernetes@1
-                      inputs:
-                        connectionType: Kubernetes Service Connection
-                        kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
-                        namespace: prod
-                        command: apply
-                        arguments: -f manifest/vote-app.yml
-                        secretType: dockerRegistry
-                        containerRegistryType: Azure Container Registry
-                      displayName: Déploiement en PROD
-                  condition: succeeded('Attente d\'une action utilisateur')
+    - task: Bash@3
+      inputs:
+        targetType: 'inline'
+        script: |
+          PRODPODS_KUBECTLOUTPUT=$(echo $(prodpods.KubernetesCliOutput) | tr -d '\r')
+          prodpodcount=$(echo $PRODPODS_KUBECTLOUTPUT | jq '.items | length')
+          echo "Total number of production pods: $prodpodcount"
+          if [ "$prodpodcount" -eq "0" ]; then
+            echo "Error: No production pods found"
+            exit 1
+          fi"
